export { default as Login } from "./Login/Login";
export { default as Home } from "./Home/Home";
export { default as Awarded } from "./Awarded/Awarded";
export { default as AddAwarded } from "./Awarded/AddAwarded";
export { default as EditSpecialties } from "./Awarded/EditSpecialties";
export { default as Calculations } from "./Calculations/Calculations";
export { default as AddCalculations } from "./Calculations/AddCalculations";
export { default as AddEmployee } from "./Calculations/AddCalculations";
export { default as Specialties } from "./Specialties/Specialties";
export { default as AddSpecialties } from "./Specialties/AddSpecialties";
export { default as CertificateSource} from "./CertificateSourse/CertificateSource";
export { default as AddSource} from "./CertificateSourse/AddSource";
